/*
 Author: Jonas, xjoniassx @ MineFactory.eu (2017)
 info@minefacotry.eu xjoniassx@gmail.com

 10% besondere Items dropchance eingestellt
 Änder ""if(zufallsZahl > 90)"" und if(zufallsZahl < 90)
 Auf z.b. 80 und du hast eine dropchance 20%
*/

Private["_weight","_weightItems"];
zufallsZahl = round(random 100);

if(zufallsZahl > 80) then {
    diag_log format ["%1", zufallsZahl];
    wonItemArray = [
        ["fuelEmpty",1],
        ["huntingKit",1],
        ["toolkit",1],
        ["ironRefined",1],
        ["heroinProcessed",1],
        ["goldBar",1],
        ["cannabis",1]
    ];
};

if(zufallsZahl < 80) then {
    wonItemArray = [
        ["qua_lenker",1]
        ["qua_sitzbank",1],
        ["qua_felge",1],
        ["qua_gepaeck_vorne",1],
        ["qua_gepaeck_hinten",1],
        ["qua_bremsscheibe",1],
        ["qua_bremsklotz",1],
        ["qua_lenkachse",1],
        ["qua_federung",1],
        ["qua_getriebe",1],
        ["qua_ruecklicht_links",1],
        ["qua_ruecklicht_rechts",1],
        ["qua_frontlicht_links",1],
        ["qua_frontlicht_rechts",1],
        ["qua_tank",1],
        ["qua_kuehlergrill",1],
        ["qua_kuehler",1],
        ["qua_zylinder",1],
        ["qua_zuendkerze",1],
        ["hatch_lenkrad",1],
        ["hatch_rueckbank",1],
        ["hatch_sitz_vorne",1],
        ["hatch_motorhaube",1],
        ["hatch_bremsscheibe",1],
        ["hatch_bremsklotz",1],
        ["hatch_lenkachse",1],
        ["hatch_federung",1],
        ["hatch_getriebe",1],
        ["hatch_ruecklicht_links",1],
        ["hatch_ruecklicht_rechts",1],
        ["hatch_frontlicht_link",1],
        ["hatch_frontlicht_rechts",1],
        ["hatch_tank",1],
        ["hatch_kuehlergrill",1],
        ["hatch_kuehler",1],
        ["hatch_Zylinder",1],
        ["hatch_zuendkerze",1],
        ["hatch_Kofferraum",1],
        ["hatch_stossfaenger_vorne",1],
        ["hatch_stossfaenger_hinten",1],
        ["hatch_rueckspiegel",1],
        ["hatch_aussenspiegel",1],
        ["hatch_katalysator",1],
        ["hatch_endtopf",1],
        ["hatch_felge",1],
        ["hatch_frontscheibe",1],
        ["hatch_seitenscheibe",1],
        ["hatch_dachscheibe",1],
        ["hatch_schaltung",1],
        ["Hatch_pedal_gas",1],
        ["hatch_pedal_bremse",1],
        ["hatch_pedal_kupplung",1],
        ["hatch_tuergriff",1],
        ["hatch_tuer_vorne_links",1],
        ["hatch_tuer_vorne_rechts",1],
        ["hatch_tuer_hinten_links",1],
        ["hatch_tuer_hinten_rechts",1],
        ["off_lenkrad",1],
        ["off_sitz",1],
        ["off_motorhaube",1],
        ["off_bremsscheibe",1],
        ["off_bremsklotz",1],
        ["off_lenkachse",1],
        ["off_federung",1],
        ["off_getriebe",1],
        ["off_ruecklicht_links",1],
        ["off_ruecklicht_rechts",1],
        ["off_frontlicht_links",1],
        ["off_frontlicht_rechts",1],
        ["off_tank",1],
        ["off_kuehlergrill",1],
        ["off_kuehler",1],
        ["off_zylinder",1],
        ["off_zuendkerze",1],
        ["off_kofferaum",1],
        ["off_stossfaenger_vorne",1],
        ["off_stossfaenger_hinten",1],
        ["off_rueckspiegel",1],
        ["off_aussenspiegel",1],
        ["off_katalysator",1],
        ["off_endtopf",1],
        ["off_felge",1],
        ["off_frontscheibe",1],
        ["off_seitenscheibe",1],
        ["off_heckscheibe",1],
        ["off_schaltung",1],
        ["off_pedal_gas",1],
        ["off_pedal_bremse",1],
        ["off_pedal_kupplung",1],
        ["off_tuergriff",1],
        ["off_tuer_links",1],
        ["off_tuer_rechts",1],
        ["suv_lenkrad",1],
        ["suv_rueckbank",1],
        ["suv_sitz_vorne",1],
        ["suv_motorhaube",1],
        ["suv_bremsscheibe",1],
        ["suv_bremsklotz",1],
        ["suv_lenkachse",1],
        ["suv_federung",1],
        ["suv_getriebe",1],
        ["suv_ruecklicht_links",1],
        ["suv_ruecklicht_rechts",1],
        ["suv_frontlicht_links",1],
        ["suv_frontlicht_rechts",1],
        ["suv_tank",1],
        ["suv_kuehlergrill",1],
        ["suv_kuehler",1],
        ["suv_zylinder",1],
        ["suv_zuendkerze",1],
        ["suv_kofferraum",1],
        ["suv_stossfaenger_vorne",1],
        ["suv_stossfaenger_hinten",1],
        ["suv_rueckspiegel",1],
        ["suv_aussenspiegel_links",1],
        ["suv_aussenspiegel_rechts",1],
        ["suv_katalysator",1],
        ["suv_endtopf",1],
        ["suv_felge",1],
        ["suv_frontscheibe",1],
        ["suv_seitenscheibe",1],
        ["suv_heckscheibe",1],
        ["suv_dachscheibe",1],
        ["suv_schaltung",1],
        ["suv_pedal_gas",1],
        ["suv_pedal_bremse",1],
        ["suv_pedal_kupplung",1],
        ["suv_tuergriff",1],
        ["suv_tuer_links",1],
        ["suv_tuer_rechts",1],
        ["kart_lenkrad",1],
        ["kart_sitz",1],
        ["kart_felge",1],
        ["kart_bremsscheibe",1],
        ["kart_bremsklotz",1],
        ["kart_lenkachse",1],
        ["kart_tank",1],
        ["kart_getriebe",1],
        ["kart_kuehler",1],
        ["kart_katalysator",1],
        ["kart_endtopf",1],
        ["kart_zylinder",1],
        ["kart_zuendkerze",1],
        ["kart_stossfaenger_vorne",1],
        ["kart_stossfaenger_hinten",1],
        ["off2_lenkrad",1],
        ["off2_sitz",1],
        ["off2_motorhaube",1],
        ["off2_bremsscheibe",1],
        ["off2_bremsklotz",1],
        ["off2_lenkachse",1],
        ["off2_federung",1],
        ["off2_getriebe",1],
        ["off2_ruecklicht_links",1],
        ["off2_ruecklicht_rechts",1],
        ["off2_frontlicht_links",1],
        ["off2_frontlicht_rechts",1],
        ["off2_tank",1],
        ["off2_kuehlergrill",1],
        ["off2_kuehler",1],
        ["off2_zylinder",1],
        ["off2_zuendkerze",1],
        ["off2_kofferaum",1],
        ["off2_stossfaenger_vorne",1],
        ["off2_stossfaenger_hinten",1],
        ["off2_rueckspiegel",1],
        ["off2_aussenspiegel",1],
        ["off2_katalysator",1],
        ["off2_endtopf",1],
        ["off2_felge",1],
        ["off2_frontscheibe",1],
        ["off2_seitenscheibe",1],
        ["off2_heckscheibe",1],
        ["off2_schaltung",1],
        ["off2_pedal_gas",1],
        ["off2_pedal_bremse",1],
        ["off2_pedal_kupplung",1],
        ["off2_tuergriff",1],
        ["off2_tuer_links",1],
        ["off2_tuer_rechts",1]
    ];
};

_wonItem = wonItemArray select floor(random(count wonItemArray));
_wonItemName = (_wonItem select 0);
_wonItemAmount = (_wonItem select 1);
//_displayName = M_CONFIG(getText,"VirtualItems",_wonItemName,"displayName");
_displayName = _wonItemName;
sleep 1;
//[format["Du bekommst %1",[_displayName]],false,"fast"] call life_fnc_NachrichtSys;
//life_fnc_NachrichtSys ist das DE100 Nachrichten System. Habe es unten ersetzt
systemChat format ["Du bekommst %1",_displayName];
[true,_wonItemName,_wonItemAmount] call life_fnc_handleInv;
